sudo: false

language: python

matrix:
 include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5
    env: TOXENV=quality
  - python: 3.6
    env: TOXENV=py36

cache:
  - pip

install:
  - pip install -U pip wheel codecov
  - make requirements

script:
  - make test

after_success:
  - codecov

deploy:
  provider: pypi
  user: edx
  password:
    secure: A2BrU6qqQHSrJ7jvxOSr1/l4HdHT5EvRWvkufMR+kdq8I8qgTlGio22Tc4OSrD5Oe7Zz7ST7q3fJFRf8Kt/gdZp7DJeeVR5gK113EvquYQUdb+wbKiBHQ3hu7JBWAjrzUQ3mDPk5DJN77dUVByYoZUmWQVMyg2fmUnQxRdertLI=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.5
    condition: '$TOX_ENV = py35'
