name: Python CI

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      branch: 
        default: 'test'
  pull_request:
    branches:
    - '**'


jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
        toxenv: [quality, django32, django40]
    steps:
    - name: setup target branch
      run: echo "target_branch=$(if ['${{ inputs.branch }}' = '']; then echo 'master'; else echo '${{ inputs.branch }}'; fi)" >> $GITHUB_ENV

    - uses: actions/checkout@v2
      with:
        ref: ${{ env.target_branch }}
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Install Dependencies
      run: pip install -r requirements/ci.txt

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: make test

    - name: Run Coverage
      if: matrix.python-version == '3.8' && matrix.toxenv=='django32'
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true
